#!/usr/bin/bash
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
sudo pacman -S ttf-fira-code wqy-zenhei st
yay -S ttf-symbola nerd-fonts-complete st
git clone https://git.suckless.org/dwm
cd dwm
sudo make clean install
echo exec dwm >> ~/.xinitrc
reboot
